ALTER TABLE "group_settings" ALTER COLUMN "photowelcome" SET DEFAULT true;
UPDATE "group_settings" SET "photowelcome" = true WHERE "photowelcome" IS NULL OR "photowelcome" = false;
ALTER TABLE "group_settings" ADD COLUMN IF NOT EXISTS "bye_config_id" integer;
CREATE SEQUENCE IF NOT EXISTS "group_settings_bye_config_id_seq";
ALTER SEQUENCE "group_settings_bye_config_id_seq" OWNED BY "group_settings"."bye_config_id";
ALTER TABLE "group_settings" ALTER COLUMN "bye_config_id" SET DEFAULT nextval('"group_settings_bye_config_id_seq"'::regclass);
UPDATE "group_settings" SET "bye_config_id" = nextval('"group_settings_bye_config_id_seq"'::regclass) WHERE "bye_config_id" IS NULL;
ALTER TABLE "group_settings" ALTER COLUMN "bye_config_id" SET NOT NULL;
ALTER TABLE "group_settings" ADD COLUMN IF NOT EXISTS "bye_registered_by" text;
ALTER TABLE "group_settings" ADD COLUMN IF NOT EXISTS "bye_hidetag" boolean DEFAULT false;
ALTER TABLE "group_settings" ALTER COLUMN "photobye" SET DEFAULT true;
UPDATE "group_settings" SET "photobye" = true WHERE "photobye" IS NULL OR "photobye" = false;
